-- Acontinuacion los Insert INTO para la creacion de las evaluaciones, las preguntas y las alternativas

--Test

INSERT INTO "USER"."TEST" (ID_TEST, NOMBRE, DESCRIPCION, PROGRAMA, UNIDAD) VALUES ('1', 'Java POO', 'Habilidades Adquiridas en la programacion orientada a objetos en java', '1', '2', 'Carlos Contreras', '15/02/20)

INSERT INTO "USER"."TEST" (ID_TEST, NOMBRE, DESCRIPCION, PROGRAMA, UNIDAD) VALUES ('2', 'Java POO', 'Habilidades Adquiridas en la programacion orientada a objetos en java', '2', '2', 'Carlos Contreras', '10/03/20)


--Preguntas

INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (1,'¿Cuál de las siguientes propiedades presenta el paradigma POO?',10,1);
--Fila 2
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (2,'¿Cuál es la descripción que crees que define mejor el concepto ''Clase'' en la programación orientada a objetos?',10,1);
--Fila 3
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (3,'¿Qué código de los siguientes tiene que ver con la Herencia?',10,1);
--Fila 4
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (4,'¿Qué elementos crees que definen a un objeto?',10,1);
--Fila 5
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (5,'¿Qué significa instanciar una clase?',10,1);
--Fila 6
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (6,'En Java, ¿a qué nos estamos refiriendo si hablamos de ''Swing''?',10,1);
--Fila 7
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (7,'¿Qué es Eclipse?',10,1);
--Fila 8
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (8,'La herencia sirve para obtener las caractiristicas de una clase',10,1);
--Fila 9
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (9,'¿Cual es la funcion de un constructor?',10,1);
--Fila 10
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (10,'¿Cuál de las siguientes propiedades presenta el paradigma POO?',10,1);
--Fila 11
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (11,'En Java, ¿Cuál de estos tipos de variable ocupa más espacio en la memoria?',10,2);
--Fila 12
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (12,'¿Qué caracter es utilizado para hacer comentario de multiples lineas?',10,2);
--Fila 13
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (13,'El siguiente código Java: public class Uno{}',10,2);
--Fila 14
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (14,'La palabra clave static sirve',10,2);
--Fila 15
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (15,'Las interfaces en java sirven para dar una mejor vista a sus programas',10,2);
--Fila 16
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (16,'¿Qué elementos crees que definen a un objeto?',10,2);
--Fila 17
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (17,'¿Qué es el bytecode en Java?',10,2);
--Fila 18
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (18,' ¿Qué código asociarías a una Interfaz en Java?',10,2);
--Fila 19
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (19,'¿Qué significa sobrecargar (overload) un método?',10,2);
--Fila 20
INSERT INTO PREGUNTAS (ID_PREGUNTAS, ENUNCIADO, PUNTAJE, TEST_ID_TEST) VALUES (20,'¿Qué es una excepción?',10,2);


--Alternativas

--Fila 1
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (1,'Ampliación de cupo automático',0,0,1);
--Fila 2
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (2,'Herencia',1,50,1);
--Fila 3
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (3,'Disminucion de cupo automático',0,0,1);
--Fila 4
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (4,'Polimorfismo',1,50,1);
--Fila 5
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (5,'Es un concepto similar al de ''Array''',0,0,2);
--Fila 6
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (6,'Es un tipo particular de variable',0,0,2);
--Fila 7
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (7,'Es un modelo o plantilla a partir de la cual creamos objetos',1,100,2);
--Fila 8
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (8,'Es una categoria de datos ordenada secuencialmente',0,0,2);
--Fila 9
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (9,'public class Componente extends Producto',1,100,3);
--Fila 10
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (10,'public class Componente inherit Porducto',0,0,3);
--Fila 11
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (11,'public class Componente implements',0,0,3);
--Fila 12
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (12,'public class Componente belong to Producto',0,0,3);
--Fila 13
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (13,'Su Tipo',0,0,4);
--Fila 14
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (14,'Su interfaz',0,0,4);
--Fila 15
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (15,'Sus Atributos',1,50,4);
--Fila 16
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (16,'Sus Métodos',1,50,4);
--Fila 17
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (17,'Crear un objeto a partir de la clase',1,100,5);
--Fila 18
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (18,'Duplicar una clase',0,0,5);
--Fila 19
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (19,'Eliminar una clase',0,0,5);
--Fila 20
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (20,'Conectar dos clases entre sí',0,0,5);
--Fila 21
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (21,'Una función utilizada ara intercambiar valores',0,0,6);
--Fila 22
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (22,'Es el sobrenombre de la versión 1.3 del JDK',0,0,6);
--Fila 23
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (23,'Un framework especifico para Android',0,0,6);
--Fila 24
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (24,'Una librería  para construir interfaces gráficas',1,100,6);
--Fila 25
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (25,'Una librería de Java',0,0,7);
--Fila 26
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (26,'Una versión de Java especial para servidores',0,0,7);
--Fila 27
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (27,'Un IDE para desarrollar aplicaciones',1,100,7);
--Fila 28
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (28,'Ninguna de las anteriores',0,0,7);
--Fila 29
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (29,'0',0,0,8);
--Fila 30
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (30,'1',1,100,8);
--Fila 31
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (31,NULL,0,0,8);
--Fila 32
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (32,NULL,0,0,8);
--Fila 33
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (33,'Construir la clase',1,100,9);
--Fila 34
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (34,'Contruir un objeto',0,0,9);
--Fila 35
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (35,'Para inicializar la clase',0,0,9);
--Fila 36
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (36,'Para asignar valores a los datos del objetos',0,0,9);
--Fila 37
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (37,'Ampliación de cupo automático',0,0,10);
--Fila 38
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (38,'Herencia',1,50,10);
--Fila 39
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (39,'Disminucion de cupo automático',0,0,10);
--Fila 40
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (40,'Polimorfismo',1,50,10);
--Fila 41
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (41,'byte',0,0,11);
--Fila 42
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (42,'boolean',1,50,11);
--Fila 43
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (43,'char',0,0,11);
--Fila 44
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (44,'int',1,50,11);
--Fila 45
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (45,'/* y */',1,100,12);
--Fila 46
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (46,' //',0,0,12);
--Fila 47
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (47,' /*/ y /*/',0,0,12);
--Fila 48
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (48,' \* y *\',0,0,12);
--Fila 49
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (49,' Declara un objeto con ámbito público',1,100,13);
--Fila 50
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (50,'Debería estar contenido en un archivo llamado Uno.java',0,0,13);
--Fila 51
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (51,'Debería ser la única clase del archivo dónde se encuentre.',0,0,13);
--Fila 52
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (52,NULL,0,0,13);
--Fila 53
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (53,'Para que los campos así declarados no puedan modificarse.',0,0,14);
--Fila 54
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (54,'Para que no se puedan crear instancias de clase.',1,100,14);
--Fila 55
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (55,'Para utilizar los métodos así declarados sin necesidad de crear una instancia.',0,0,14);
--Fila 56
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (56,NULL,0,0,14);
--Fila 57
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (57,'1',0,0,15);
--Fila 58
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (58,'0',1,0,15);
--Fila 59
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (59,NULL,0,0,15);
--Fila 60
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (60,NULL,0,0,15);
--Fila 61
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (61,'Su Tipo',0,0,16);
--Fila 62
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (62,'Su interfaz',0,0,16);
--Fila 63
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (63,'Sus Atributos',1,50,16);
--Fila 64
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (64,'Sus Métodos',1,50,16);
--Fila 65
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (65,'El formato de intercambio de datos',0,0,17);
--Fila 66
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (66,'El formato que obtenemos tras compilar un fuente .java',1,50,17);
--Fila 67
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (67,'Es un lenguaje intermedio',1,50,17);
--Fila 68
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (68,'Un depurador de código',0,0,17);
--Fila 69
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (69,'public interface Series',1,50,18);
--Fila 70
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (70,'public class Componente interface Product',0,0,18);
--Fila 71
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (71,'Componente cp = new Componente (interfaz)',0,0,18);
--Fila 72
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (72,'public class Componente implements Printable',1,50,18);
--Fila 73
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (73,'Editarlo para modificar su comportamiento',0,0,19);
--Fila 74
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (74,'Cambiarle el nombre dejándolo con la misma funcionalidad',0,0,19);
--Fila 75
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (75,'Crear un método con el mismo nombre pero diferentes argumentos',1,100,19);
--Fila 76
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (76,'Añadirle funcionalidades a un método',0,0,19);
--Fila 77
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (77,'Un error que lanza un método cuando algo va mal',1,100,20);
--Fila 78
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (78,'Un objeto que no puede ser instanciado',0,0,20);
--Fila 79
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (79,'Un bucle que no finaliza',0,0,20);
--Fila 80
INSERT INTO ALTERNATIVAS (ID_ALTERNATIVAS, DESCRIPCION, VALOR_LOGICO, PORCENTAJE, PREGUNTAS_ID_PREGUNTAS) VALUES (80,'Un tipo de evento muy utilizado al crear interfaces',0,0,20);
